local _, TM = ...
-- UTF-8 translations. Build names, slash commands and the NUKE token are not translated.
local locales = {
    enUS = {
        MERGE = "Merge",
        CLEAN = "Clean",
        NUKE = "Nuke",
        REFRESH = "Refresh",
        CONFIRM = "Confirm",
        BACK = "Back",
        STOP = "Stop",
        SCOPE = "Merge and Clean: current specialization. Nuke: all specializations.",
        BUSY = "Deletion is in progress. Wait for it to finish.",
        RETAIL_REQUIRED = "This addon requires WoW Retail and its talent APIs.",
        COMBAT = "Wait until you leave combat.",
        DEAD = "Resurrect before modifying loadouts.",
        STAGED = "Apply or undo your pending talent changes first.",
        CHANGED = "Loadouts have changed. Review the list and confirm again.",
        EXPORT_FAILED = "Could not export %s. Nothing has been deleted.",
        DELETED = "Deleted: %d.",
        REMAINING = " Remaining: %d.",
        DELETE_STOPPED = "Deletion stopped.",
        DELETE_REFUSED = "WoW could not delete “%s”. No further loadouts have been processed.",
        DELETE_TIMEOUT = "WoW did not confirm the deletion of “%s”.",
        NAME_INVALID = "Enter a valid name without color codes.",
        RENAME_FAILED = "WoW could not save the name. Try another name. No loadouts have been deleted.",
        NUKE_REQUIRED = "You must type exactly NUKE.",
        LIST_CHANGED = "The list has changed. Confirm again.",
        TYPE_EXACT = "Type exactly %s.",
        NAME_REQUIRED = "Enter a name for the loadout.",
        CONFIRM_ERROR = "Confirmation error: %s",
        OP_FAILED = "The operation could not be completed.",
        OP_DONE = "Operation completed.",
        NO_DUPLICATES = "No duplicate loadouts.",
        PICK_GROUP = "Choose Merge in the group you want to merge.",
        MERGE_TITLE = "Merge — name the resulting loadout",
        MERGE_INTRO = "These loadouts have identical talents:\n\n",
        MERGE_DETAIL = "\n\nThe first will be renamed and the others deleted. The first loadout's talents and settings will be preserved.\n\nSuggested name (editable):",
        CLEAN_INTRO = "The first loadout in each group will be kept, in WoW's order. The other copies will be deleted. Unique loadouts will be kept.\n",
        GROUP_KEEP = "Group %d — KEEP: %s",
        REMOVE = "DELETE: %s",
        CLEAN_TITLE = "Clean — review and confirm",
        NO_SAVED = "No saved loadouts.",
        NUKE_INTRO = "ALL saved loadouts for this character, across ALL specializations, will be deleted. The character's active talents will not be reset.\n",
        NUKE_PROMPT = "\nType exactly NUKE to confirm.",
        NUKE_TITLE = "Nuke — delete all loadouts",
        COMBAT_ACTIONS = "In combat: Merge, Clean and Nuke are blocked.",
        PROGRESS = "Deleting loadouts: %d/%d%s",
        STOPPING = " · stopping…",
        WAIT_CONFIRM = " · waiting for WoW confirmation.",
        RETURN_REVIEW = " Return to the list to review what remains.",
        API_UNAVAILABLE = "Talent API unavailable. Use /tm status for diagnostics.",
        GROUP_DUPLICATES = "Group %d · %d identical loadouts",
        UNIQUE_HEADER = "Unique loadouts / missing exports",
        NO_EXPORT_SUFFIX = " (no export for backup)",
        SUMMARY = "%d loadouts · %d duplicate groups",
        UNREADABLE_SUFFIX = " · %d unreadable",
        STATUS = "v%s · Retail API: %s · menu: %s · loadouts: %d · groups: %d",
        STATUS_COMBAT = "Reading paused during combat: the counters above may be out of date.",
        DIAGNOSTICS = "Spec: %s · IDs without spec: %d · IDs with spec: %d · missing info: %d · active internal configs: %d · missing exports: %d · compared by nodes: %d",
        OK = "OK",
        UNAVAILABLE = "unavailable",
        REGISTERED = "registered",
        NOTES = "Group, merge and clean duplicate talent loadouts.",
    },
    esES = {
        MERGE = "Fusionar",
        CLEAN = "Limpiar",
        NUKE = "Eliminar todo",
        REFRESH = "Actualizar",
        CONFIRM = "Confirmar",
        BACK = "Volver",
        STOP = "Detener",
        SCOPE = "Fusionar y Limpiar: especialización actual. Eliminar todo: todas las especializaciones.",
        BUSY = "Hay un borrado en curso. Espera a que termine.",
        RETAIL_REQUIRED = "Este addon necesita WoW Retail y sus API de talentos.",
        COMBAT = "Espera a salir de combate.",
        DEAD = "Resucita antes de modificar las builds.",
        STAGED = "Aplica o deshaz los cambios de talentos pendientes primero.",
        CHANGED = "Las builds han cambiado. Revisa la lista y confirma de nuevo.",
        EXPORT_FAILED = "No se pudo exportar %s. No se ha borrado nada.",
        DELETED = "Borradas: %d.",
        REMAINING = " Pendientes: %d.",
        DELETE_STOPPED = "Borrado detenido.",
        DELETE_REFUSED = "WoW no pudo borrar «%s». No se ha continuado con las siguientes builds.",
        DELETE_TIMEOUT = "WoW no confirmó el borrado de «%s».",
        NAME_INVALID = "Escribe un nombre válido sin códigos de color.",
        RENAME_FAILED = "WoW no pudo guardar el nombre. Prueba otro nombre. No se ha borrado ninguna build.",
        NUKE_REQUIRED = "Debes escribir exactamente NUKE.",
        LIST_CHANGED = "La lista ha cambiado. Confirma de nuevo.",
        TYPE_EXACT = "Escribe exactamente %s.",
        NAME_REQUIRED = "Escribe un nombre para la build.",
        CONFIRM_ERROR = "Error al confirmar: %s",
        OP_FAILED = "No se pudo completar la operación.",
        OP_DONE = "Operación completada.",
        NO_DUPLICATES = "No hay builds repetidas.",
        PICK_GROUP = "Elige Fusionar en el grupo que quieras fusionar.",
        MERGE_TITLE = "Fusionar — nombre de la build resultante",
        MERGE_INTRO = "Estas builds tienen los mismos talentos:\n\n",
        MERGE_DETAIL = "\n\nSe renombrará la primera y se borrarán las demás. Se conservarán los talentos y los ajustes de la primera.\n\nNombre sugerido (puedes editarlo):",
        CLEAN_INTRO = "Se conservará la primera build de cada grupo, según el orden de WoW. Las copias restantes se borrarán. Las builds únicas se conservarán.\n",
        GROUP_KEEP = "Grupo %d — CONSERVAR: %s",
        REMOVE = "BORRAR: %s",
        CLEAN_TITLE = "Limpiar — revisar y confirmar",
        NO_SAVED = "No hay builds guardadas.",
        NUKE_INTRO = "Se borrarán TODAS las builds guardadas de este personaje, en TODAS sus especializaciones. Los talentos activos del personaje no se restablecen.\n",
        NUKE_PROMPT = "\nEscribe exactamente NUKE para confirmar.",
        NUKE_TITLE = "Eliminar todo — borrar todas las builds",
        COMBAT_ACTIONS = "En combate: Fusionar, Limpiar y Eliminar todo están bloqueados.",
        PROGRESS = "Borrando builds: %d/%d%s",
        STOPPING = " · deteniendo…",
        WAIT_CONFIRM = " · espera a que WoW confirme.",
        RETURN_REVIEW = " Vuelve a la lista para revisar lo que queda.",
        API_UNAVAILABLE = "API de talentos no disponible. Usa /tm status para diagnosticar.",
        GROUP_DUPLICATES = "Grupo %d · %d builds iguales",
        UNIQUE_HEADER = "Builds únicas / sin exportación",
        NO_EXPORT_SUFFIX = " (sin exportación para copia)",
        SUMMARY = "%d builds · %d grupos repetidos",
        UNREADABLE_SUFFIX = " · %d sin leer",
        STATUS = "v%s · API retail: %s · menú: %s · builds: %d · grupos: %d",
        STATUS_COMBAT = "Lectura pausada por combate: los contadores anteriores pueden estar desactualizados.",
        DIAGNOSTICS = "Spec: %s · IDs sin spec: %d · IDs con spec: %d · sin información: %d · internos activos: %d · sin exportación: %d · comparadas por nodos: %d",
        OK = "OK",
        UNAVAILABLE = "no disponible",
        REGISTERED = "registrado",
        NOTES = "Agrupa, fusiona y limpia builds de talentos repetidas.",
    },
    deDE = {
        MERGE = "Zusammenführen",
        CLEAN = "Bereinigen",
        NUKE = "Alle löschen",
        REFRESH = "Aktualisieren",
        CONFIRM = "Bestätigen",
        BACK = "Zurück",
        STOP = "Stoppen",
        SCOPE = "Zusammenführen und Bereinigen: aktuelle Spezialisierung. Alle löschen: alle Spezialisierungen.",
        BUSY = "Ein Löschvorgang läuft. Warte, bis er abgeschlossen ist.",
        RETAIL_REQUIRED = "Dieses Addon benötigt WoW Retail und dessen Talent-APIs.",
        COMBAT = "Warte, bis du den Kampf verlassen hast.",
        DEAD = "Lass dich wiederbeleben, bevor du Talentkonfigurationen änderst.",
        STAGED = "Übernimm oder verwirf zuerst deine ausstehenden Talentänderungen.",
        CHANGED = "Die Talentkonfigurationen wurden geändert. Prüfe die Liste und bestätige erneut.",
        EXPORT_FAILED = "%s konnte nicht exportiert werden. Es wurde nichts gelöscht.",
        DELETED = "Gelöscht: %d.",
        REMAINING = " Verbleibend: %d.",
        DELETE_STOPPED = "Löschvorgang gestoppt.",
        DELETE_REFUSED = "WoW konnte „%s“ nicht löschen. Weitere Talentkonfigurationen wurden nicht bearbeitet.",
        DELETE_TIMEOUT = "WoW hat das Löschen von „%s“ nicht bestätigt.",
        NAME_INVALID = "Gib einen gültigen Namen ohne Farbcodes ein.",
        RENAME_FAILED = "WoW konnte den Namen nicht speichern. Versuche einen anderen Namen. Es wurde keine Talentkonfiguration gelöscht.",
        NUKE_REQUIRED = "Du musst genau NUKE eingeben.",
        LIST_CHANGED = "Die Liste wurde geändert. Bestätige erneut.",
        TYPE_EXACT = "Gib genau %s ein.",
        NAME_REQUIRED = "Gib einen Namen für die Talentkonfiguration ein.",
        CONFIRM_ERROR = "Fehler beim Bestätigen: %s",
        OP_FAILED = "Der Vorgang konnte nicht abgeschlossen werden.",
        OP_DONE = "Vorgang abgeschlossen.",
        NO_DUPLICATES = "Keine doppelten Talentkonfigurationen.",
        PICK_GROUP = "Wähle Zusammenführen in der gewünschten Gruppe.",
        MERGE_TITLE = "Zusammenführen — Name der neuen Talentkonfiguration",
        MERGE_INTRO = "Diese Talentkonfigurationen haben identische Talente:\n\n",
        MERGE_DETAIL = "\n\nDie erste wird umbenannt, die übrigen werden gelöscht. Talente und Einstellungen der ersten bleiben erhalten.\n\nNamensvorschlag (bearbeitbar):",
        CLEAN_INTRO = "Die erste Talentkonfiguration jeder Gruppe bleibt in der WoW-Reihenfolge erhalten. Die übrigen Kopien werden gelöscht. Einzigartige Konfigurationen bleiben erhalten.\n",
        GROUP_KEEP = "Gruppe %d — BEHALTEN: %s",
        REMOVE = "LÖSCHEN: %s",
        CLEAN_TITLE = "Bereinigen — prüfen und bestätigen",
        NO_SAVED = "Keine gespeicherten Talentkonfigurationen.",
        NUKE_INTRO = "ALLE gespeicherten Talentkonfigurationen dieses Charakters für ALLE Spezialisierungen werden gelöscht. Die aktiven Talente werden nicht zurückgesetzt.\n",
        NUKE_PROMPT = "\nGib zur Bestätigung genau NUKE ein.",
        NUKE_TITLE = "Alle löschen — alle Talentkonfigurationen entfernen",
        COMBAT_ACTIONS = "Im Kampf: Zusammenführen, Bereinigen und Alle löschen sind gesperrt.",
        PROGRESS = "Talentkonfigurationen löschen: %d/%d%s",
        STOPPING = " · wird gestoppt…",
        WAIT_CONFIRM = " · warte auf WoW-Bestätigung.",
        RETURN_REVIEW = " Kehre zur Liste zurück, um die verbleibenden Konfigurationen zu prüfen.",
        API_UNAVAILABLE = "Talent-API nicht verfügbar. Verwende /tm status zur Diagnose.",
        GROUP_DUPLICATES = "Gruppe %d · %d identische Talentkonfigurationen",
        UNIQUE_HEADER = "Einzigartige Konfigurationen / fehlende Exporte",
        NO_EXPORT_SUFFIX = " (kein Export für die Sicherung)",
        SUMMARY = "%d Konfigurationen · %d doppelte Gruppen",
        UNREADABLE_SUFFIX = " · %d nicht lesbar",
        STATUS = "v%s · Retail-API: %s · Menü: %s · Konfigurationen: %d · Gruppen: %d",
        STATUS_COMBAT = "Lesen im Kampf pausiert: Die obigen Zähler können veraltet sein.",
        DIAGNOSTICS = "Spez.: %s · IDs ohne Spez.: %d · IDs mit Spez.: %d · ohne Daten: %d · aktive interne Konfigurationen: %d · ohne Export: %d · nach Knoten verglichen: %d",
        OK = "OK",
        UNAVAILABLE = "nicht verfügbar",
        REGISTERED = "registriert",
        NOTES = "Doppelte Talentkonfigurationen gruppieren, zusammenführen und bereinigen.",
    },
    frFR = {
        MERGE = "Fusionner",
        CLEAN = "Nettoyer",
        NUKE = "Tout supprimer",
        REFRESH = "Actualiser",
        CONFIRM = "Confirmer",
        BACK = "Retour",
        STOP = "Arrêter",
        SCOPE = "Fusionner et Nettoyer : spécialisation actuelle. Tout supprimer : toutes les spécialisations.",
        BUSY = "Une suppression est en cours. Attendez qu’elle se termine.",
        RETAIL_REQUIRED = "Cet addon nécessite WoW Retail et ses API de talents.",
        COMBAT = "Attendez de quitter le combat.",
        DEAD = "Ressuscitez avant de modifier les configurations.",
        STAGED = "Appliquez ou annulez d’abord les modifications de talents en attente.",
        CHANGED = "Les configurations ont changé. Vérifiez la liste et confirmez à nouveau.",
        EXPORT_FAILED = "Impossible d’exporter %s. Rien n’a été supprimé.",
        DELETED = "Supprimées : %d.",
        REMAINING = " Restantes : %d.",
        DELETE_STOPPED = "Suppression arrêtée.",
        DELETE_REFUSED = "WoW n’a pas pu supprimer « %s ». Les configurations suivantes n’ont pas été traitées.",
        DELETE_TIMEOUT = "WoW n’a pas confirmé la suppression de « %s ».",
        NAME_INVALID = "Saisissez un nom valide sans codes de couleur.",
        RENAME_FAILED = "WoW n’a pas pu enregistrer le nom. Essayez un autre nom. Aucune configuration n’a été supprimée.",
        NUKE_REQUIRED = "Vous devez saisir exactement NUKE.",
        LIST_CHANGED = "La liste a changé. Confirmez à nouveau.",
        TYPE_EXACT = "Saisissez exactement %s.",
        NAME_REQUIRED = "Saisissez un nom pour la configuration.",
        CONFIRM_ERROR = "Erreur de confirmation : %s",
        OP_FAILED = "L’opération n’a pas pu être terminée.",
        OP_DONE = "Opération terminée.",
        NO_DUPLICATES = "Aucune configuration en double.",
        PICK_GROUP = "Choisissez Fusionner dans le groupe souhaité.",
        MERGE_TITLE = "Fusionner — nom de la configuration obtenue",
        MERGE_INTRO = "Ces configurations ont les mêmes talents :\n\n",
        MERGE_DETAIL = "\n\nLa première sera renommée et les autres supprimées. Les talents et les réglages de la première seront conservés.\n\nNom proposé (modifiable) :",
        CLEAN_INTRO = "La première configuration de chaque groupe sera conservée, dans l’ordre de WoW. Les autres copies seront supprimées. Les configurations uniques seront conservées.\n",
        GROUP_KEEP = "Groupe %d — CONSERVER : %s",
        REMOVE = "SUPPRIMER : %s",
        CLEAN_TITLE = "Nettoyer — vérifier et confirmer",
        NO_SAVED = "Aucune configuration enregistrée.",
        NUKE_INTRO = "TOUTES les configurations enregistrées de ce personnage, pour TOUTES ses spécialisations, seront supprimées. Ses talents actifs ne seront pas réinitialisés.\n",
        NUKE_PROMPT = "\nSaisissez exactement NUKE pour confirmer.",
        NUKE_TITLE = "Tout supprimer — supprimer toutes les configurations",
        COMBAT_ACTIONS = "En combat : Fusionner, Nettoyer et Tout supprimer sont bloqués.",
        PROGRESS = "Suppression des configurations : %d/%d%s",
        STOPPING = " · arrêt en cours…",
        WAIT_CONFIRM = " · en attente de confirmation de WoW.",
        RETURN_REVIEW = " Revenez à la liste pour vérifier ce qui reste.",
        API_UNAVAILABLE = "API de talents indisponible. Utilisez /tm status pour le diagnostic.",
        GROUP_DUPLICATES = "Groupe %d · %d configurations identiques",
        UNIQUE_HEADER = "Configurations uniques / exports manquants",
        NO_EXPORT_SUFFIX = " (pas d’export pour la sauvegarde)",
        SUMMARY = "%d configurations · %d groupes en double",
        UNREADABLE_SUFFIX = " · %d illisibles",
        STATUS = "v%s · API Retail : %s · menu : %s · configurations : %d · groupes : %d",
        STATUS_COMBAT = "Lecture suspendue en combat : les compteurs ci-dessus peuvent être périmés.",
        DIAGNOSTICS = "Spé. : %s · IDs sans spé. : %d · IDs avec spé. : %d · sans données : %d · configurations internes actives : %d · sans export : %d · comparées par nœuds : %d",
        OK = "OK",
        UNAVAILABLE = "indisponible",
        REGISTERED = "enregistré",
        NOTES = "Regroupe, fusionne et nettoie les configurations de talents en double.",
    },
    itIT = {
        MERGE = "Unisci",
        CLEAN = "Pulisci",
        NUKE = "Elimina tutto",
        REFRESH = "Aggiorna",
        CONFIRM = "Conferma",
        BACK = "Indietro",
        STOP = "Interrompi",
        SCOPE = "Unisci e Pulisci: specializzazione attuale. Elimina tutto: tutte le specializzazioni.",
        BUSY = "È in corso un’eliminazione. Attendi che termini.",
        RETAIL_REQUIRED = "Questo addon richiede WoW Retail e le sue API dei talenti.",
        COMBAT = "Attendi di uscire dal combattimento.",
        DEAD = "Resuscita prima di modificare le configurazioni.",
        STAGED = "Applica o annulla prima le modifiche ai talenti in sospeso.",
        CHANGED = "Le configurazioni sono cambiate. Controlla l’elenco e conferma di nuovo.",
        EXPORT_FAILED = "Impossibile esportare %s. Non è stato eliminato nulla.",
        DELETED = "Eliminate: %d.",
        REMAINING = " Rimanenti: %d.",
        DELETE_STOPPED = "Eliminazione interrotta.",
        DELETE_REFUSED = "WoW non ha potuto eliminare «%s». Le configurazioni successive non sono state elaborate.",
        DELETE_TIMEOUT = "WoW non ha confermato l’eliminazione di «%s».",
        NAME_INVALID = "Inserisci un nome valido senza codici colore.",
        RENAME_FAILED = "WoW non ha potuto salvare il nome. Prova un altro nome. Nessuna configurazione è stata eliminata.",
        NUKE_REQUIRED = "Devi scrivere esattamente NUKE.",
        LIST_CHANGED = "L’elenco è cambiato. Conferma di nuovo.",
        TYPE_EXACT = "Scrivi esattamente %s.",
        NAME_REQUIRED = "Inserisci un nome per la configurazione.",
        CONFIRM_ERROR = "Errore di conferma: %s",
        OP_FAILED = "Impossibile completare l’operazione.",
        OP_DONE = "Operazione completata.",
        NO_DUPLICATES = "Nessuna configurazione duplicata.",
        PICK_GROUP = "Scegli Unisci nel gruppo che vuoi unire.",
        MERGE_TITLE = "Unisci — nome della configurazione risultante",
        MERGE_INTRO = "Queste configurazioni hanno gli stessi talenti:\n\n",
        MERGE_DETAIL = "\n\nLa prima verrà rinominata e le altre eliminate. I talenti e le impostazioni della prima verranno conservati.\n\nNome suggerito (modificabile):",
        CLEAN_INTRO = "Verrà conservata la prima configurazione di ogni gruppo, nell’ordine di WoW. Le altre copie verranno eliminate. Le configurazioni uniche verranno conservate.\n",
        GROUP_KEEP = "Gruppo %d — CONSERVA: %s",
        REMOVE = "ELIMINA: %s",
        CLEAN_TITLE = "Pulisci — controlla e conferma",
        NO_SAVED = "Nessuna configurazione salvata.",
        NUKE_INTRO = "Verranno eliminate TUTTE le configurazioni salvate di questo personaggio, per TUTTE le specializzazioni. I talenti attivi non verranno azzerati.\n",
        NUKE_PROMPT = "\nScrivi esattamente NUKE per confermare.",
        NUKE_TITLE = "Elimina tutto — elimina tutte le configurazioni",
        COMBAT_ACTIONS = "In combattimento: Unisci, Pulisci ed Elimina tutto sono bloccati.",
        PROGRESS = "Eliminazione delle configurazioni: %d/%d%s",
        STOPPING = " · interruzione in corso…",
        WAIT_CONFIRM = " · in attesa della conferma di WoW.",
        RETURN_REVIEW = " Torna all’elenco per controllare ciò che rimane.",
        API_UNAVAILABLE = "API dei talenti non disponibile. Usa /tm status per la diagnosi.",
        GROUP_DUPLICATES = "Gruppo %d · %d configurazioni identiche",
        UNIQUE_HEADER = "Configurazioni uniche / esportazioni mancanti",
        NO_EXPORT_SUFFIX = " (nessuna esportazione per il backup)",
        SUMMARY = "%d configurazioni · %d gruppi duplicati",
        UNREADABLE_SUFFIX = " · %d illeggibili",
        STATUS = "v%s · API Retail: %s · menu: %s · configurazioni: %d · gruppi: %d",
        STATUS_COMBAT = "Lettura sospesa durante il combattimento: i contatori precedenti potrebbero non essere aggiornati.",
        DIAGNOSTICS = "Spec.: %s · ID senza spec.: %d · ID con spec.: %d · senza dati: %d · configurazioni interne attive: %d · senza esportazione: %d · confrontate per nodi: %d",
        OK = "OK",
        UNAVAILABLE = "non disponibile",
        REGISTERED = "registrato",
        NOTES = "Raggruppa, unisce e pulisce le configurazioni di talenti duplicate.",
    },
    ptBR = {
        MERGE = "Mesclar",
        CLEAN = "Limpar",
        NUKE = "Apagar tudo",
        REFRESH = "Atualizar",
        CONFIRM = "Confirmar",
        BACK = "Voltar",
        STOP = "Parar",
        SCOPE = "Mesclar e Limpar: especialização atual. Apagar tudo: todas as especializações.",
        BUSY = "Uma exclusão está em andamento. Aguarde a conclusão.",
        RETAIL_REQUIRED = "Este addon requer WoW Retail e suas APIs de talentos.",
        COMBAT = "Aguarde sair de combate.",
        DEAD = "Ressuscite antes de modificar as configurações.",
        STAGED = "Primeiro, aplique ou desfaça as alterações de talentos pendentes.",
        CHANGED = "As configurações mudaram. Revise a lista e confirme novamente.",
        EXPORT_FAILED = "Não foi possível exportar %s. Nada foi apagado.",
        DELETED = "Apagadas: %d.",
        REMAINING = " Restantes: %d.",
        DELETE_STOPPED = "Exclusão interrompida.",
        DELETE_REFUSED = "O WoW não conseguiu apagar «%s». As configurações seguintes não foram processadas.",
        DELETE_TIMEOUT = "O WoW não confirmou a exclusão de «%s».",
        NAME_INVALID = "Digite um nome válido sem códigos de cor.",
        RENAME_FAILED = "O WoW não conseguiu salvar o nome. Tente outro nome. Nenhuma configuração foi apagada.",
        NUKE_REQUIRED = "Você deve digitar exatamente NUKE.",
        LIST_CHANGED = "A lista mudou. Confirme novamente.",
        TYPE_EXACT = "Digite exatamente %s.",
        NAME_REQUIRED = "Digite um nome para a configuração.",
        CONFIRM_ERROR = "Erro ao confirmar: %s",
        OP_FAILED = "Não foi possível concluir a operação.",
        OP_DONE = "Operação concluída.",
        NO_DUPLICATES = "Não há configurações duplicadas.",
        PICK_GROUP = "Escolha Mesclar no grupo que deseja mesclar.",
        MERGE_TITLE = "Mesclar — nome da configuração resultante",
        MERGE_INTRO = "Estas configurações têm os mesmos talentos:\n\n",
        MERGE_DETAIL = "\n\nA primeira será renomeada e as demais serão apagadas. Os talentos e os ajustes da primeira serão mantidos.\n\nNome sugerido (editável):",
        CLEAN_INTRO = "A primeira configuração de cada grupo será mantida, na ordem do WoW. As outras cópias serão apagadas. As configurações únicas serão mantidas.\n",
        GROUP_KEEP = "Grupo %d — MANTER: %s",
        REMOVE = "APAGAR: %s",
        CLEAN_TITLE = "Limpar — revisar e confirmar",
        NO_SAVED = "Não há configurações salvas.",
        NUKE_INTRO = "TODAS as configurações salvas deste personagem, de TODAS as especializações, serão apagadas. Os talentos ativos não serão redefinidos.\n",
        NUKE_PROMPT = "\nDigite exatamente NUKE para confirmar.",
        NUKE_TITLE = "Apagar tudo — apagar todas as configurações",
        COMBAT_ACTIONS = "Em combate: Mesclar, Limpar e Apagar tudo estão bloqueados.",
        PROGRESS = "Apagando configurações: %d/%d%s",
        STOPPING = " · interrompendo…",
        WAIT_CONFIRM = " · aguardando confirmação do WoW.",
        RETURN_REVIEW = " Volte à lista para revisar o que resta.",
        API_UNAVAILABLE = "API de talentos indisponível. Use /tm status para diagnóstico.",
        GROUP_DUPLICATES = "Grupo %d · %d configurações idênticas",
        UNIQUE_HEADER = "Configurações únicas / exportações ausentes",
        NO_EXPORT_SUFFIX = " (sem exportação para backup)",
        SUMMARY = "%d configurações · %d grupos duplicados",
        UNREADABLE_SUFFIX = " · %d não puderam ser lidas",
        STATUS = "v%s · API Retail: %s · menu: %s · configurações: %d · grupos: %d",
        STATUS_COMBAT = "Leitura pausada durante o combate: os contadores acima podem estar desatualizados.",
        DIAGNOSTICS = "Esp.: %s · IDs sem esp.: %d · IDs com esp.: %d · sem informações: %d · configurações internas ativas: %d · sem exportação: %d · comparadas por nós: %d",
        OK = "OK",
        UNAVAILABLE = "indisponível",
        REGISTERED = "registrado",
        NOTES = "Agrupa, mescla e limpa configurações de talentos duplicadas.",
    },
    ruRU = {
        MERGE = "Объединить",
        CLEAN = "Очистить",
        NUKE = "Удалить всё",
        REFRESH = "Обновить",
        CONFIRM = "Подтвердить",
        BACK = "Назад",
        STOP = "Остановить",
        SCOPE = "Объединить и Очистить: текущая специализация. Удалить всё: все специализации.",
        BUSY = "Идёт удаление. Дождитесь его завершения.",
        RETAIL_REQUIRED = "Для этого аддона требуется WoW Retail и API талантов.",
        COMBAT = "Дождитесь окончания боя.",
        DEAD = "Воскресните, прежде чем изменять наборы талантов.",
        STAGED = "Сначала примените или отмените несохранённые изменения талантов.",
        CHANGED = "Наборы талантов изменились. Проверьте список и подтвердите снова.",
        EXPORT_FAILED = "Не удалось экспортировать %s. Ничего не удалено.",
        DELETED = "Удалено: %d.",
        REMAINING = " Осталось: %d.",
        DELETE_STOPPED = "Удаление остановлено.",
        DELETE_REFUSED = "WoW не удалось удалить «%s». Следующие наборы не обрабатывались.",
        DELETE_TIMEOUT = "WoW не подтвердил удаление «%s».",
        NAME_INVALID = "Введите допустимое имя без кодов цвета.",
        RENAME_FAILED = "WoW не удалось сохранить имя. Попробуйте другое имя. Ни один набор не удалён.",
        NUKE_REQUIRED = "Нужно ввести в точности NUKE.",
        LIST_CHANGED = "Список изменился. Подтвердите снова.",
        TYPE_EXACT = "Введите в точности %s.",
        NAME_REQUIRED = "Введите имя набора талантов.",
        CONFIRM_ERROR = "Ошибка подтверждения: %s",
        OP_FAILED = "Не удалось завершить операцию.",
        OP_DONE = "Операция завершена.",
        NO_DUPLICATES = "Повторяющихся наборов талантов нет.",
        PICK_GROUP = "Выберите «Объединить» в нужной группе.",
        MERGE_TITLE = "Объединить — имя итогового набора",
        MERGE_INTRO = "В этих наборах выбраны одинаковые таланты:\n\n",
        MERGE_DETAIL = "\n\nПервый набор будет переименован, остальные — удалены. Таланты и настройки первого набора сохранятся.\n\nПредлагаемое имя (можно изменить):",
        CLEAN_INTRO = "Первый набор в каждой группе будет сохранён в порядке WoW. Остальные копии будут удалены. Уникальные наборы сохранятся.\n",
        GROUP_KEEP = "Группа %d — СОХРАНИТЬ: %s",
        REMOVE = "УДАЛИТЬ: %s",
        CLEAN_TITLE = "Очистить — проверить и подтвердить",
        NO_SAVED = "Сохранённых наборов талантов нет.",
        NUKE_INTRO = "Будут удалены ВСЕ сохранённые наборы этого персонажа для ВСЕХ специализаций. Активные таланты персонажа не сбрасываются.\n",
        NUKE_PROMPT = "\nДля подтверждения введите в точности NUKE.",
        NUKE_TITLE = "Удалить всё — удалить все наборы",
        COMBAT_ACTIONS = "В бою: объединение, очистка и удаление всех наборов заблокированы.",
        PROGRESS = "Удаление наборов: %d/%d%s",
        STOPPING = " · остановка…",
        WAIT_CONFIRM = " · ожидание подтверждения WoW.",
        RETURN_REVIEW = " Вернитесь к списку, чтобы проверить оставшиеся наборы.",
        API_UNAVAILABLE = "API талантов недоступен. Для диагностики используйте /tm status.",
        GROUP_DUPLICATES = "Группа %d · одинаковых наборов: %d",
        UNIQUE_HEADER = "Уникальные наборы / без экспорта",
        NO_EXPORT_SUFFIX = " (нет экспорта для резервной копии)",
        SUMMARY = "Наборов: %d · групп повторов: %d",
        UNREADABLE_SUFFIX = " · не удалось прочитать: %d",
        STATUS = "v%s · API Retail: %s · меню: %s · наборов: %d · групп: %d",
        STATUS_COMBAT = "Чтение приостановлено на время боя: счётчики выше могут быть устаревшими.",
        DIAGNOSTICS = "Спец.: %s · ID без спец.: %d · ID со спец.: %d · без данных: %d · активных внутренних конфигураций: %d · без экспорта: %d · сравнено по узлам: %d",
        OK = "OK",
        UNAVAILABLE = "недоступно",
        REGISTERED = "зарегистрировано",
        NOTES = "Группирует, объединяет и очищает повторяющиеся наборы талантов.",
    },
    koKR = {
        MERGE = "병합",
        CLEAN = "중복 정리",
        NUKE = "모두 삭제",
        REFRESH = "새로 고침",
        CONFIRM = "확인",
        BACK = "뒤로",
        STOP = "중지",
        SCOPE = "병합 및 중복 정리: 현재 전문화. 모두 삭제: 모든 전문화.",
        BUSY = "삭제 작업이 진행 중입니다. 완료될 때까지 기다려 주세요.",
        RETAIL_REQUIRED = "이 애드온에는 WoW 본 서버와 해당 특성 API가 필요합니다.",
        COMBAT = "전투가 끝날 때까지 기다려 주세요.",
        DEAD = "특성 구성을 변경하려면 먼저 부활하세요.",
        STAGED = "먼저 적용 대기 중인 특성 변경 사항을 적용하거나 취소하세요.",
        CHANGED = "특성 구성이 변경되었습니다. 목록을 검토하고 다시 확인하세요.",
        EXPORT_FAILED = "%s 내보내기에 실패했습니다. 아무것도 삭제하지 않았습니다.",
        DELETED = "삭제됨: %d.",
        REMAINING = " 남음: %d.",
        DELETE_STOPPED = "삭제 작업이 중지되었습니다.",
        DELETE_REFUSED = "WoW에서 ‘%s’ 삭제에 실패했습니다. 다음 특성 구성은 처리하지 않았습니다.",
        DELETE_TIMEOUT = "WoW에서 ‘%s’ 삭제를 확인하지 못했습니다.",
        NAME_INVALID = "색상 코드가 없는 유효한 이름을 입력하세요.",
        RENAME_FAILED = "WoW에서 이름을 저장하지 못했습니다. 다른 이름을 입력하세요. 특성 구성은 삭제되지 않았습니다.",
        NUKE_REQUIRED = "정확히 NUKE를 입력해야 합니다.",
        LIST_CHANGED = "목록이 변경되었습니다. 다시 확인하세요.",
        TYPE_EXACT = "정확히 %s를 입력하세요.",
        NAME_REQUIRED = "특성 구성의 이름을 입력하세요.",
        CONFIRM_ERROR = "확인 오류: %s",
        OP_FAILED = "작업을 완료하지 못했습니다.",
        OP_DONE = "작업이 완료되었습니다.",
        NO_DUPLICATES = "중복된 특성 구성이 없습니다.",
        PICK_GROUP = "병합할 그룹에서 병합을 선택하세요.",
        MERGE_TITLE = "병합 — 결과 특성 구성의 이름",
        MERGE_INTRO = "다음 특성 구성은 선택한 특성이 같습니다:\n\n",
        MERGE_DETAIL = "\n\n첫 번째 구성의 이름을 변경하고 나머지는 삭제합니다. 첫 번째 구성의 특성과 설정은 유지됩니다.\n\n추천 이름(수정 가능):",
        CLEAN_INTRO = "WoW 순서에 따라 각 그룹의 첫 번째 구성을 유지합니다. 나머지 중복 구성은 삭제하며, 고유한 구성은 유지합니다.\n",
        GROUP_KEEP = "그룹 %d — 유지: %s",
        REMOVE = "삭제: %s",
        CLEAN_TITLE = "중복 정리 — 검토 및 확인",
        NO_SAVED = "저장된 특성 구성이 없습니다.",
        NUKE_INTRO = "이 캐릭터의 모든 전문화에 저장된 특성 구성을 전부 삭제합니다. 현재 적용된 특성은 초기화하지 않습니다.\n",
        NUKE_PROMPT = "\n확인하려면 정확히 NUKE를 입력하세요.",
        NUKE_TITLE = "모두 삭제 — 모든 특성 구성 삭제",
        COMBAT_ACTIONS = "전투 중: 병합, 중복 정리, 모두 삭제를 사용할 수 없습니다.",
        PROGRESS = "특성 구성 삭제 중: %d/%d%s",
        STOPPING = " · 중지 중…",
        WAIT_CONFIRM = " · WoW 확인을 기다리는 중입니다.",
        RETURN_REVIEW = " 목록으로 돌아가 남은 구성을 검토하세요.",
        API_UNAVAILABLE = "특성 API를 사용할 수 없습니다. 진단하려면 /tm status를 사용하세요.",
        GROUP_DUPLICATES = "그룹 %d · 동일한 특성 구성 %d개",
        UNIQUE_HEADER = "고유한 특성 구성 / 내보내기 없음",
        NO_EXPORT_SUFFIX = " (백업용 내보내기 없음)",
        SUMMARY = "특성 구성 %d개 · 중복 그룹 %d개",
        UNREADABLE_SUFFIX = " · 읽지 못함 %d개",
        STATUS = "v%s · 본 서버 API: %s · 메뉴: %s · 특성 구성: %d · 그룹: %d",
        STATUS_COMBAT = "전투 중에는 읽기가 일시 중지됩니다. 위 집계는 최신 정보가 아닐 수 있습니다.",
        DIAGNOSTICS = "전문화: %s · 전문화 미지정 ID: %d · 전문화 지정 ID: %d · 정보 없음: %d · 활성 내부 구성: %d · 내보내기 없음: %d · 노드 비교: %d",
        OK = "정상",
        UNAVAILABLE = "사용 불가",
        REGISTERED = "등록됨",
        NOTES = "중복된 특성 구성을 그룹으로 묶고 병합하며 정리합니다.",
    },
    zhCN = {
        MERGE = "合并",
        CLEAN = "清理重复",
        NUKE = "全部删除",
        REFRESH = "刷新",
        CONFIRM = "确认",
        BACK = "返回",
        STOP = "停止",
        SCOPE = "合并和清理重复：当前专精。全部删除：所有专精。",
        BUSY = "正在删除，请等待操作完成。",
        RETAIL_REQUIRED = "此插件需要 WoW 正式服及其天赋 API。",
        COMBAT = "请等待脱离战斗。",
        DEAD = "请先复活，再修改天赋配置。",
        STAGED = "请先应用或撤销尚未确认的天赋更改。",
        CHANGED = "天赋配置已更改，请检查列表并重新确认。",
        EXPORT_FAILED = "无法导出 %s。未删除任何配置。",
        DELETED = "已删除：%d。",
        REMAINING = " 剩余：%d。",
        DELETE_STOPPED = "删除已停止。",
        DELETE_REFUSED = "WoW 无法删除“%s”。未继续处理后续配置。",
        DELETE_TIMEOUT = "WoW 未确认删除“%s”。",
        NAME_INVALID = "请输入不含颜色代码的有效名称。",
        RENAME_FAILED = "WoW 无法保存名称，请尝试其他名称。未删除任何天赋配置。",
        NUKE_REQUIRED = "必须准确输入 NUKE。",
        LIST_CHANGED = "列表已更改，请重新确认。",
        TYPE_EXACT = "请准确输入 %s。",
        NAME_REQUIRED = "请输入天赋配置名称。",
        CONFIRM_ERROR = "确认时出错：%s",
        OP_FAILED = "无法完成操作。",
        OP_DONE = "操作已完成。",
        NO_DUPLICATES = "没有重复的天赋配置。",
        PICK_GROUP = "请在要合并的分组中选择“合并”。",
        MERGE_TITLE = "合并 — 为结果配置命名",
        MERGE_INTRO = "以下配置选择了相同的天赋：\n\n",
        MERGE_DETAIL = "\n\n将重命名第一份配置并删除其余副本。保留第一份配置的天赋和设置。\n\n建议名称（可修改）：",
        CLEAN_INTRO = "按 WoW 的顺序保留每组的第一份配置，删除其他重复副本。独有的配置将保留。\n",
        GROUP_KEEP = "分组 %d — 保留：%s",
        REMOVE = "删除：%s",
        CLEAN_TITLE = "清理重复 — 检查并确认",
        NO_SAVED = "没有已保存的天赋配置。",
        NUKE_INTRO = "将删除此角色所有专精的全部已保存天赋配置。不会重置角色当前生效的天赋。\n",
        NUKE_PROMPT = "\n请准确输入 NUKE 以确认。",
        NUKE_TITLE = "全部删除 — 删除所有天赋配置",
        COMBAT_ACTIONS = "战斗中：合并、清理重复和全部删除已禁用。",
        PROGRESS = "正在删除配置：%d/%d%s",
        STOPPING = " · 正在停止…",
        WAIT_CONFIRM = " · 正在等待 WoW 确认。",
        RETURN_REVIEW = " 请返回列表检查剩余配置。",
        API_UNAVAILABLE = "天赋 API 不可用。请使用 /tm status 进行诊断。",
        GROUP_DUPLICATES = "分组 %d · %d 份相同配置",
        UNIQUE_HEADER = "独有配置 / 无导出数据",
        NO_EXPORT_SUFFIX = "（无可用于备份的导出数据）",
        SUMMARY = "%d 份配置 · %d 个重复分组",
        UNREADABLE_SUFFIX = " · %d 份无法读取",
        STATUS = "v%s · 正式服 API：%s · 菜单：%s · 配置：%d · 分组：%d",
        STATUS_COMBAT = "战斗期间暂停读取：上述计数可能不是最新数据。",
        DIAGNOSTICS = "专精：%s · 未指定专精 ID：%d · 指定专精 ID：%d · 无信息：%d · 生效的内部配置：%d · 无导出数据：%d · 按节点比较：%d",
        OK = "正常",
        UNAVAILABLE = "不可用",
        REGISTERED = "已注册",
        NOTES = "对重复的天赋配置进行分组、合并和清理。",
    },
    zhTW = {
        MERGE = "合併",
        CLEAN = "清理重複",
        NUKE = "全部刪除",
        REFRESH = "重新整理",
        CONFIRM = "確認",
        BACK = "返回",
        STOP = "停止",
        SCOPE = "合併及清理重複：目前專精。全部刪除：所有專精。",
        BUSY = "正在刪除，請等待操作完成。",
        RETAIL_REQUIRED = "此插件需要 WoW 正式版及其天賦 API。",
        COMBAT = "請等待脫離戰鬥。",
        DEAD = "請先復活，再修改天賦配置。",
        STAGED = "請先套用或撤銷尚未確認的天賦變更。",
        CHANGED = "天賦配置已變更，請檢查清單並重新確認。",
        EXPORT_FAILED = "無法匯出 %s。未刪除任何配置。",
        DELETED = "已刪除：%d。",
        REMAINING = " 剩餘：%d。",
        DELETE_STOPPED = "刪除已停止。",
        DELETE_REFUSED = "WoW 無法刪除「%s」。未繼續處理後續配置。",
        DELETE_TIMEOUT = "WoW 未確認刪除「%s」。",
        NAME_INVALID = "請輸入不含顏色代碼的有效名稱。",
        RENAME_FAILED = "WoW 無法儲存名稱，請嘗試其他名稱。未刪除任何天賦配置。",
        NUKE_REQUIRED = "必須準確輸入 NUKE。",
        LIST_CHANGED = "清單已變更，請重新確認。",
        TYPE_EXACT = "請準確輸入 %s。",
        NAME_REQUIRED = "請輸入天賦配置名稱。",
        CONFIRM_ERROR = "確認時發生錯誤：%s",
        OP_FAILED = "無法完成操作。",
        OP_DONE = "操作已完成。",
        NO_DUPLICATES = "沒有重複的天賦配置。",
        PICK_GROUP = "請在要合併的群組中選擇「合併」。",
        MERGE_TITLE = "合併 — 為結果配置命名",
        MERGE_INTRO = "以下配置選擇了相同的天賦：\n\n",
        MERGE_DETAIL = "\n\n將重新命名第一份配置並刪除其餘副本。保留第一份配置的天賦和設定。\n\n建議名稱（可修改）：",
        CLEAN_INTRO = "依 WoW 的順序保留每組的第一份配置，刪除其他重複副本。獨有的配置將保留。\n",
        GROUP_KEEP = "群組 %d — 保留：%s",
        REMOVE = "刪除：%s",
        CLEAN_TITLE = "清理重複 — 檢查並確認",
        NO_SAVED = "沒有已儲存的天賦配置。",
        NUKE_INTRO = "將刪除此角色所有專精的全部已儲存天賦配置。不會重設角色目前生效的天賦。\n",
        NUKE_PROMPT = "\n請準確輸入 NUKE 以確認。",
        NUKE_TITLE = "全部刪除 — 刪除所有天賦配置",
        COMBAT_ACTIONS = "戰鬥中：合併、清理重複及全部刪除已停用。",
        PROGRESS = "正在刪除配置：%d/%d%s",
        STOPPING = " · 正在停止…",
        WAIT_CONFIRM = " · 正在等待 WoW 確認。",
        RETURN_REVIEW = " 請返回清單檢查剩餘配置。",
        API_UNAVAILABLE = "天賦 API 無法使用。請使用 /tm status 進行診斷。",
        GROUP_DUPLICATES = "群組 %d · %d 份相同配置",
        UNIQUE_HEADER = "獨有配置 / 無匯出資料",
        NO_EXPORT_SUFFIX = "（無可用於備份的匯出資料）",
        SUMMARY = "%d 份配置 · %d 個重複群組",
        UNREADABLE_SUFFIX = " · %d 份無法讀取",
        STATUS = "v%s · 正式版 API：%s · 選單：%s · 配置：%d · 群組：%d",
        STATUS_COMBAT = "戰鬥期間暫停讀取：上述計數可能不是最新資料。",
        DIAGNOSTICS = "專精：%s · 未指定專精 ID：%d · 指定專精 ID：%d · 無資訊：%d · 生效的內部配置：%d · 無匯出資料：%d · 依節點比較：%d",
        OK = "正常",
        UNAVAILABLE = "無法使用",
        REGISTERED = "已註冊",
        NOTES = "將重複的天賦配置分組、合併並清理。",
    },
}
-- Specialization-scoped deletion.
locales.enUS.NUKE_SELECT_TITLE = "Nuke — choose specializations"
locales.enUS.NUKE_SELECT_INTRO = "Select the specializations whose saved loadouts you want to delete. Unchecked specializations and active talents are preserved. Type NUKE to confirm."
locales.enUS.NUKE_SELECTION_COUNT = "%d specializations selected · %d loadouts"
locales.enUS.NUKE_NO_SELECTION = "Select at least one specialization with saved loadouts."
locales.enUS.SPEC_LOADOUT_COUNT = "%d saved loadouts"
locales.enUS.SCOPE = "Merge and Clean: current specialization. Nuke: selected specializations."
locales.esES.NUKE_SELECT_TITLE = "Eliminar — elegir especializaciones"
locales.esES.NUKE_SELECT_INTRO = "Selecciona las especializaciones cuyas builds guardadas quieres borrar. Las no marcadas y los talentos activos se conservan. Escribe NUKE para confirmar."
locales.esES.NUKE_SELECTION_COUNT = "%d especializaciones seleccionadas · %d builds"
locales.esES.NUKE_NO_SELECTION = "Selecciona al menos una especialización con builds guardadas."
locales.esES.SPEC_LOADOUT_COUNT = "%d builds guardadas"
locales.esES.SCOPE = "Fusionar y Limpiar: especialización actual. Eliminar: especializaciones seleccionadas."
locales.deDE.NUKE_SELECT_TITLE = "Löschen — Spezialisierungen auswählen"
locales.deDE.NUKE_SELECT_INTRO = "Wähle die Spezialisierungen, deren gespeicherte Talentkonfigurationen du löschen möchtest. Nicht ausgewählte Spezialisierungen und aktive Talente bleiben erhalten. Gib zur Bestätigung NUKE ein."
locales.deDE.NUKE_SELECTION_COUNT = "%d Spezialisierungen ausgewählt · %d Konfigurationen"
locales.deDE.NUKE_NO_SELECTION = "Wähle mindestens eine Spezialisierung mit gespeicherten Konfigurationen."
locales.deDE.SPEC_LOADOUT_COUNT = "%d gespeicherte Konfigurationen"
locales.deDE.SCOPE = "Zusammenführen und Bereinigen: aktuelle Spezialisierung. Löschen: ausgewählte Spezialisierungen."
locales.frFR.NUKE_SELECT_TITLE = "Supprimer — choisir les spécialisations"
locales.frFR.NUKE_SELECT_INTRO = "Sélectionnez les spécialisations dont vous souhaitez supprimer les configurations enregistrées. Les spécialisations non cochées et les talents actifs sont conservés. Saisissez NUKE pour confirmer."
locales.frFR.NUKE_SELECTION_COUNT = "%d spécialisations sélectionnées · %d configurations"
locales.frFR.NUKE_NO_SELECTION = "Sélectionnez au moins une spécialisation avec des configurations enregistrées."
locales.frFR.SPEC_LOADOUT_COUNT = "%d configurations enregistrées"
locales.frFR.SCOPE = "Fusionner et Nettoyer : spécialisation actuelle. Supprimer : spécialisations sélectionnées."
locales.itIT.NUKE_SELECT_TITLE = "Elimina — scegli le specializzazioni"
locales.itIT.NUKE_SELECT_INTRO = "Seleziona le specializzazioni di cui vuoi eliminare le configurazioni salvate. Le specializzazioni non selezionate e i talenti attivi vengono conservati. Scrivi NUKE per confermare."
locales.itIT.NUKE_SELECTION_COUNT = "%d specializzazioni selezionate · %d configurazioni"
locales.itIT.NUKE_NO_SELECTION = "Seleziona almeno una specializzazione con configurazioni salvate."
locales.itIT.SPEC_LOADOUT_COUNT = "%d configurazioni salvate"
locales.itIT.SCOPE = "Unisci e Pulisci: specializzazione attuale. Elimina: specializzazioni selezionate."
locales.ptBR.NUKE_SELECT_TITLE = "Apagar — escolher especializações"
locales.ptBR.NUKE_SELECT_INTRO = "Selecione as especializações cujas configurações salvas deseja apagar. As especializações não marcadas e os talentos ativos serão mantidos. Digite NUKE para confirmar."
locales.ptBR.NUKE_SELECTION_COUNT = "%d especializações selecionadas · %d configurações"
locales.ptBR.NUKE_NO_SELECTION = "Selecione pelo menos uma especialização com configurações salvas."
locales.ptBR.SPEC_LOADOUT_COUNT = "%d configurações salvas"
locales.ptBR.SCOPE = "Mesclar e Limpar: especialização atual. Apagar: especializações selecionadas."
locales.ruRU.NUKE_SELECT_TITLE = "Удалить — выбрать специализации"
locales.ruRU.NUKE_SELECT_INTRO = "Выберите специализации, чьи сохранённые наборы нужно удалить. Неотмеченные специализации и активные таланты сохранятся. Введите NUKE для подтверждения."
locales.ruRU.NUKE_SELECTION_COUNT = "Выбрано специализаций: %d · наборов: %d"
locales.ruRU.NUKE_NO_SELECTION = "Выберите хотя бы одну специализацию с сохранёнными наборами."
locales.ruRU.SPEC_LOADOUT_COUNT = "Сохранённых наборов: %d"
locales.ruRU.SCOPE = "Объединить и Очистить: текущая специализация. Удалить: выбранные специализации."
locales.koKR.NUKE_SELECT_TITLE = "삭제 — 전문화 선택"
locales.koKR.NUKE_SELECT_INTRO = "저장된 특성 구성을 삭제할 전문화를 선택하세요. 선택하지 않은 전문화와 현재 적용된 특성은 유지됩니다. 확인하려면 NUKE를 입력하세요."
locales.koKR.NUKE_SELECTION_COUNT = "선택한 전문화 %d개 · 특성 구성 %d개"
locales.koKR.NUKE_NO_SELECTION = "저장된 특성 구성이 있는 전문화를 하나 이상 선택하세요."
locales.koKR.SPEC_LOADOUT_COUNT = "저장된 특성 구성 %d개"
locales.koKR.SCOPE = "병합 및 중복 정리: 현재 전문화. 삭제: 선택한 전문화."
locales.zhCN.NUKE_SELECT_TITLE = "删除 — 选择专精"
locales.zhCN.NUKE_SELECT_INTRO = "选择要删除已保存天赋配置的专精。未勾选的专精和当前生效的天赋将保留。输入 NUKE 以确认。"
locales.zhCN.NUKE_SELECTION_COUNT = "已选择 %d 个专精 · %d 份配置"
locales.zhCN.NUKE_NO_SELECTION = "请至少选择一个有已保存配置的专精。"
locales.zhCN.SPEC_LOADOUT_COUNT = "%d 份已保存配置"
locales.zhCN.SCOPE = "合并和清理重复：当前专精。删除：所选专精。"
locales.zhTW.NUKE_SELECT_TITLE = "刪除 — 選擇專精"
locales.zhTW.NUKE_SELECT_INTRO = "選擇要刪除已儲存天賦配置的專精。未勾選的專精和目前生效的天賦將保留。輸入 NUKE 以確認。"
locales.zhTW.NUKE_SELECTION_COUNT = "已選擇 %d 個專精 · %d 份配置"
locales.zhTW.NUKE_NO_SELECTION = "請至少選擇一個有已儲存配置的專精。"
locales.zhTW.SPEC_LOADOUT_COUNT = "%d 份已儲存配置"
locales.zhTW.SCOPE = "合併及清理重複：目前專精。刪除：所選專精。"
locales.enUS.UNDO = "Undo"
locales.enUS.RESTORE = "Restore"
locales.enUS.HISTORY_INTRO = "Last 10 operations. Restore each specialization while it is active. Existing copies are kept."
locales.enUS.HISTORY_EMPTY = "No operations saved yet."
locales.enUS.RESTORE_OPEN_TALENTS = "Open your own talent tree to restore."
locales.enUS.RESTORE_INVALID = "This backup is incompatible with the current talent tree."
locales.enUS.RESTORE_RESULT = "Restored: %d of %d."
locales.enUS.RESTORE_SWITCH = "Activate this specialization first, then return to restore."
locales.enUS.RESTORE_NOTHING = "These builds are already present."
locales.enUS.RESTORE_FAILED = "WoW refused the import. Check the loadout limit."
locales.enUS.RESTORE_TIMEOUT = "Import confirmation timed out. Check the saved builds before retrying."
locales.enUS.RESTORE_PENDING = "%d builds to restore"
locales.enUS.RESTORE_DETAIL = "Restore the names and talents listed below. Existing builds are kept. Action bars and equipment sets are not included in backups."
locales.enUS.RESTORE_PROGRESS = "Restoring: %d / %d"
locales.esES.UNDO = "Deshacer"
locales.esES.RESTORE = "Restaurar"
locales.esES.HISTORY_INTRO = "Últimas 10 operaciones. Restaura cada especialización estando activa. Se conservan las copias existentes."
locales.esES.HISTORY_EMPTY = "Todavía no hay operaciones guardadas."
locales.esES.RESTORE_OPEN_TALENTS = "Abre tu árbol de talentos para restaurar."
locales.esES.RESTORE_INVALID = "Esta copia no es compatible con el árbol de talentos actual."
locales.esES.RESTORE_RESULT = "Restauradas: %d de %d."
locales.esES.RESTORE_SWITCH = "Activa primero esta especialización y vuelve para restaurar."
locales.esES.RESTORE_NOTHING = "Estas builds ya están guardadas."
locales.esES.RESTORE_FAILED = "WoW rechazó la importación. Comprueba el límite de builds."
locales.esES.RESTORE_TIMEOUT = "La importación no se confirmó a tiempo. Revisa las builds antes de reintentar."
locales.esES.RESTORE_PENDING = "%d builds por restaurar"
locales.esES.RESTORE_DETAIL = "Restaura los nombres y talentos indicados abajo. Conserva las builds existentes. Las copias no incluyen barras de acción ni conjuntos de equipo."
locales.esES.RESTORE_PROGRESS = "Restaurando: %d / %d"
locales.deDE.UNDO = "Rückgängig"
locales.deDE.RESTORE = "Wiederherstellen"
locales.deDE.HISTORY_INTRO = "Letzte 10 Vorgänge. Zum Wiederherstellen muss die Spezialisierung aktiv sein. Vorhandene Kopien bleiben erhalten."
locales.deDE.HISTORY_EMPTY = "Noch keine Vorgänge gespeichert."
locales.deDE.RESTORE_OPEN_TALENTS = "Öffne deinen Talentbaum zum Wiederherstellen."
locales.deDE.RESTORE_INVALID = "Diese Sicherung ist mit dem aktuellen Talentbaum inkompatibel."
locales.deDE.RESTORE_RESULT = "Wiederhergestellt: %d von %d."
locales.deDE.RESTORE_SWITCH = "Aktiviere zuerst diese Spezialisierung und kehre dann zurück."
locales.deDE.RESTORE_NOTHING = "Diese Konfigurationen sind bereits vorhanden."
locales.deDE.RESTORE_FAILED = "WoW hat den Import abgelehnt. Prüfe das Konfigurationslimit."
locales.deDE.RESTORE_TIMEOUT = "Import nicht rechtzeitig bestätigt. Prüfe vor einem erneuten Versuch die Konfigurationen."
locales.deDE.RESTORE_PENDING = "%d Konfigurationen wiederherstellen"
locales.deDE.RESTORE_DETAIL = "Stellt die folgenden Namen und Talente wieder her. Vorhandene Konfigurationen bleiben erhalten. Aktionsleisten und Ausrüstungssets sind nicht gesichert."
locales.deDE.RESTORE_PROGRESS = "Wiederherstellen: %d / %d"
locales.frFR.UNDO = "Annuler"
locales.frFR.RESTORE = "Restaurer"
locales.frFR.HISTORY_INTRO = "10 dernières opérations. Activez la spécialisation à restaurer. Les copies existantes sont conservées."
locales.frFR.HISTORY_EMPTY = "Aucune opération enregistrée."
locales.frFR.RESTORE_OPEN_TALENTS = "Ouvrez votre arbre de talents pour restaurer."
locales.frFR.RESTORE_INVALID = "Cette sauvegarde est incompatible avec l’arbre de talents actuel."
locales.frFR.RESTORE_RESULT = "Restaurées : %d sur %d."
locales.frFR.RESTORE_SWITCH = "Activez cette spécialisation, puis revenez pour restaurer."
locales.frFR.RESTORE_NOTHING = "Ces configurations sont déjà présentes."
locales.frFR.RESTORE_FAILED = "WoW a refusé l’importation. Vérifiez la limite de configurations."
locales.frFR.RESTORE_TIMEOUT = "Importation non confirmée à temps. Vérifiez les configurations avant de réessayer."
locales.frFR.RESTORE_PENDING = "%d configurations à restaurer"
locales.frFR.RESTORE_DETAIL = "Restaure les noms et talents ci-dessous. Conserve les configurations existantes. Les barres d’action et ensembles d’équipement ne sont pas sauvegardés."
locales.frFR.RESTORE_PROGRESS = "Restauration : %d / %d"
locales.itIT.UNDO = "Annulla"
locales.itIT.RESTORE = "Ripristina"
locales.itIT.HISTORY_INTRO = "Ultime 10 operazioni. Attiva la specializzazione da ripristinare. Le copie esistenti vengono conservate."
locales.itIT.HISTORY_EMPTY = "Nessuna operazione salvata."
locales.itIT.RESTORE_OPEN_TALENTS = "Apri il tuo albero dei talenti per ripristinare."
locales.itIT.RESTORE_INVALID = "Il backup non è compatibile con l’albero dei talenti attuale."
locales.itIT.RESTORE_RESULT = "Ripristinate: %d di %d."
locales.itIT.RESTORE_SWITCH = "Attiva prima questa specializzazione e torna per ripristinare."
locales.itIT.RESTORE_NOTHING = "Queste configurazioni sono già presenti."
locales.itIT.RESTORE_FAILED = "WoW ha rifiutato l’importazione. Controlla il limite di configurazioni."
locales.itIT.RESTORE_TIMEOUT = "Importazione non confermata in tempo. Controlla le configurazioni prima di riprovare."
locales.itIT.RESTORE_PENDING = "%d configurazioni da ripristinare"
locales.itIT.RESTORE_DETAIL = "Ripristina i nomi e talenti seguenti. Conserva le configurazioni esistenti. Il backup non include barre delle azioni o set di equipaggiamento."
locales.itIT.RESTORE_PROGRESS = "Ripristino: %d / %d"
locales.ptBR.UNDO = "Desfazer"
locales.ptBR.RESTORE = "Restaurar"
locales.ptBR.HISTORY_INTRO = "Últimas 10 operações. Ative a especialização a restaurar. As cópias existentes serão mantidas."
locales.ptBR.HISTORY_EMPTY = "Nenhuma operação salva."
locales.ptBR.RESTORE_OPEN_TALENTS = "Abra sua árvore de talentos para restaurar."
locales.ptBR.RESTORE_INVALID = "Este backup é incompatível com a árvore de talentos atual."
locales.ptBR.RESTORE_RESULT = "Restauradas: %d de %d."
locales.ptBR.RESTORE_SWITCH = "Ative esta especialização primeiro e volte para restaurar."
locales.ptBR.RESTORE_NOTHING = "Estas configurações já estão presentes."
locales.ptBR.RESTORE_FAILED = "O WoW recusou a importação. Verifique o limite de configurações."
locales.ptBR.RESTORE_TIMEOUT = "A importação não foi confirmada a tempo. Verifique as configurações antes de tentar novamente."
locales.ptBR.RESTORE_PENDING = "%d configurações para restaurar"
locales.ptBR.RESTORE_DETAIL = "Restaura os nomes e talentos abaixo. Mantém as configurações existentes. Os backups não incluem barras de ação ou conjuntos de equipamento."
locales.ptBR.RESTORE_PROGRESS = "Restaurando: %d / %d"
locales.ruRU.UNDO = "Отменить"
locales.ruRU.RESTORE = "Восстановить"
locales.ruRU.HISTORY_INTRO = "Последние 10 операций. Для восстановления активируйте нужную специализацию. Существующие копии сохраняются."
locales.ruRU.HISTORY_EMPTY = "Сохранённых операций пока нет."
locales.ruRU.RESTORE_OPEN_TALENTS = "Откройте своё дерево талантов для восстановления."
locales.ruRU.RESTORE_INVALID = "Эта копия несовместима с текущим деревом талантов."
locales.ruRU.RESTORE_RESULT = "Восстановлено: %d из %d."
locales.ruRU.RESTORE_SWITCH = "Сначала активируйте эту специализацию и вернитесь для восстановления."
locales.ruRU.RESTORE_NOTHING = "Эти наборы уже сохранены."
locales.ruRU.RESTORE_FAILED = "WoW отклонил импорт. Проверьте ограничение числа наборов."
locales.ruRU.RESTORE_TIMEOUT = "Подтверждение импорта не получено вовремя. Проверьте наборы перед повторной попыткой."
locales.ruRU.RESTORE_PENDING = "Наборов для восстановления: %d"
locales.ruRU.RESTORE_DETAIL = "Восстанавливает имена и таланты ниже. Существующие наборы сохраняются. Панели команд и комплекты экипировки не входят в резервные копии."
locales.ruRU.RESTORE_PROGRESS = "Восстановление: %d / %d"
locales.koKR.UNDO = "실행 취소"
locales.koKR.RESTORE = "복원"
locales.koKR.HISTORY_INTRO = "최근 작업 10개. 복원할 전문화를 활성화하세요. 기존 구성은 유지됩니다."
locales.koKR.HISTORY_EMPTY = "저장된 작업이 없습니다."
locales.koKR.RESTORE_OPEN_TALENTS = "복원하려면 자신의 특성 창을 여세요."
locales.koKR.RESTORE_INVALID = "현재 특성 트리와 호환되지 않는 백업입니다."
locales.koKR.RESTORE_RESULT = "복원: %d / %d."
locales.koKR.RESTORE_SWITCH = "먼저 이 전문화를 활성화한 다음 돌아와서 복원하세요."
locales.koKR.RESTORE_NOTHING = "이 특성 구성은 이미 저장되어 있습니다."
locales.koKR.RESTORE_FAILED = "WoW가 가져오기를 거부했습니다. 구성 개수 제한을 확인하세요."
locales.koKR.RESTORE_TIMEOUT = "가져오기 확인 시간이 초과되었습니다. 재시도 전에 구성을 확인하세요."
locales.koKR.RESTORE_PENDING = "복원할 구성 %d개"
locales.koKR.RESTORE_DETAIL = "아래 이름과 특성을 복원합니다. 기존 구성은 유지됩니다. 행동 단축바와 장비 세트는 백업에 포함되지 않습니다."
locales.koKR.RESTORE_PROGRESS = "복원 중: %d / %d"
locales.zhCN.UNDO = "撤销"
locales.zhCN.RESTORE = "恢复"
locales.zhCN.HISTORY_INTRO = "最近10次操作。请激活要恢复的专精。保留现有配置。"
locales.zhCN.HISTORY_EMPTY = "尚无已保存的操作。"
locales.zhCN.RESTORE_OPEN_TALENTS = "请打开自己的天赋树以恢复。"
locales.zhCN.RESTORE_INVALID = "此备份与当前天赋树不兼容。"
locales.zhCN.RESTORE_RESULT = "已恢复：%d / %d。"
locales.zhCN.RESTORE_SWITCH = "请先激活此专精，然后返回恢复。"
locales.zhCN.RESTORE_NOTHING = "这些配置已存在。"
locales.zhCN.RESTORE_FAILED = "WoW拒绝导入。请检查配置数量上限。"
locales.zhCN.RESTORE_TIMEOUT = "导入确认超时。重试前请检查已保存的配置。"
locales.zhCN.RESTORE_PENDING = "%d份配置待恢复"
locales.zhCN.RESTORE_DETAIL = "恢复以下名称和天赋。保留现有配置。备份不包括动作条或装备方案。"
locales.zhCN.RESTORE_PROGRESS = "恢复中：%d / %d"
locales.zhTW.UNDO = "復原"
locales.zhTW.RESTORE = "還原"
locales.zhTW.HISTORY_INTRO = "最近10次操作。請啟用要還原的專精。保留現有配置。"
locales.zhTW.HISTORY_EMPTY = "尚無已儲存的操作。"
locales.zhTW.RESTORE_OPEN_TALENTS = "請開啟自己的天賦樹以還原。"
locales.zhTW.RESTORE_INVALID = "此備份與目前天賦樹不相容。"
locales.zhTW.RESTORE_RESULT = "已還原：%d / %d。"
locales.zhTW.RESTORE_SWITCH = "請先啟用此專精，然後返回還原。"
locales.zhTW.RESTORE_NOTHING = "這些配置已存在。"
locales.zhTW.RESTORE_FAILED = "WoW拒絕匯入。請檢查配置數量上限。"
locales.zhTW.RESTORE_TIMEOUT = "匯入確認逾時。重試前請檢查已儲存的配置。"
locales.zhTW.RESTORE_PENDING = "%d份配置待還原"
locales.zhTW.RESTORE_DETAIL = "還原以下名稱和天賦。保留現有配置。備份不包含快捷列或裝備套裝。"
locales.zhTW.RESTORE_PROGRESS = "還原中：%d / %d"
locales.enUS.HIDE_UNIQUE = "Hide unique builds"
locales.enUS.LOADOUT_CELL = "Loadouts %d"
locales.enUS.NO_DUPLICATED_GROUPS = "No duplicated groups"
locales.enUS.DUPLICATE_CELL = "Duplicate groups %d"
locales.enUS.NUKE_CONFIRM_TITLE = "Nuke — confirm deletion"
locales.enUS.NUKE_CONFIRM_INTRO = "You are about to delete %d saved loadouts from: %s. Other specializations and active talents are preserved. Type NUKE or 123123 to confirm."
locales.enUS.SELECT_SPECS = "Select at least one specialization first."
locales.enUS.MERGE_BATCH_INTRO = "Review each duplicate group in the selected specializations and edit its resulting name. The first copy is renamed; the other copies are removed."
locales.enUS.SCOPE = "Merge, Clean and Nuke affect selected specializations."
locales.enUS.NUKE_REQUIRED = "Type NUKE or 123123 to confirm."
locales.esES.HIDE_UNIQUE = "Ocultar builds únicas"
locales.esES.LOADOUT_CELL = "Builds %d"
locales.esES.NO_DUPLICATED_GROUPS = "Sin grupos repetidos"
locales.esES.DUPLICATE_CELL = "Grupos repetidos %d"
locales.esES.NUKE_CONFIRM_TITLE = "Nuke — confirmar borrado"
locales.esES.NUKE_CONFIRM_INTRO = "Vas a borrar %d builds guardadas de: %s. Las demás especializaciones y los talentos activos se conservarán. Escribe NUKE o 123123 para confirmar."
locales.esES.SELECT_SPECS = "Selecciona primero al menos una especialización."
locales.esES.MERGE_BATCH_INTRO = "Revisa cada grupo repetido de las especializaciones seleccionadas y edita su nombre resultante. Se renombra la primera copia y se eliminan las demás."
locales.esES.SCOPE = "Merge, Clean y Nuke afectan a las especializaciones seleccionadas."
locales.esES.NUKE_REQUIRED = "Escribe NUKE o 123123 para confirmar."
locales.deDE.HIDE_UNIQUE = "Einzigartige Builds ausblenden"
locales.deDE.LOADOUT_CELL = "Konfigurationen %d"
locales.deDE.NO_DUPLICATED_GROUPS = "Keine doppelten Gruppen"
locales.deDE.DUPLICATE_CELL = "Doppelte Gruppen %d"
locales.deDE.NUKE_CONFIRM_TITLE = "Nuke — Löschen bestätigen"
locales.deDE.NUKE_CONFIRM_INTRO = "Du löschst %d gespeicherte Konfigurationen aus: %s. Andere Spezialisierungen und aktive Talente bleiben erhalten. Gib NUKE oder 123123 ein."
locales.deDE.SELECT_SPECS = "Wähle zuerst mindestens eine Spezialisierung."
locales.deDE.MERGE_BATCH_INTRO = "Prüfe jede doppelte Gruppe der gewählten Spezialisierungen und bearbeite ihren neuen Namen. Die erste Kopie wird umbenannt, die übrigen werden entfernt."
locales.deDE.SCOPE = "Zusammenführen, Bereinigen und Nuke betreffen gewählte Spezialisierungen."
locales.deDE.NUKE_REQUIRED = "Gib NUKE oder 123123 zum Bestätigen ein."
locales.frFR.HIDE_UNIQUE = "Masquer les builds uniques"
locales.frFR.LOADOUT_CELL = "Configurations %d"
locales.frFR.NO_DUPLICATED_GROUPS = "Aucun groupe en double"
locales.frFR.DUPLICATE_CELL = "Groupes en double %d"
locales.frFR.NUKE_CONFIRM_TITLE = "Nuke — confirmer la suppression"
locales.frFR.NUKE_CONFIRM_INTRO = "Vous allez supprimer %d configurations de : %s. Les autres spécialisations et talents actifs seront conservés. Saisissez NUKE ou 123123 pour confirmer."
locales.frFR.SELECT_SPECS = "Sélectionnez au moins une spécialisation."
locales.frFR.MERGE_BATCH_INTRO = "Vérifiez chaque groupe en double des spécialisations sélectionnées et modifiez son nouveau nom. La première copie est renommée et les autres supprimées."
locales.frFR.SCOPE = "Fusionner, Nettoyer et Nuke concernent les spécialisations sélectionnées."
locales.frFR.NUKE_REQUIRED = "Saisissez NUKE ou 123123 pour confirmer."
locales.itIT.HIDE_UNIQUE = "Nascondi le build uniche"
locales.itIT.LOADOUT_CELL = "Configurazioni %d"
locales.itIT.NO_DUPLICATED_GROUPS = "Nessun gruppo duplicato"
locales.itIT.DUPLICATE_CELL = "Gruppi duplicati %d"
locales.itIT.NUKE_CONFIRM_TITLE = "Nuke — conferma eliminazione"
locales.itIT.NUKE_CONFIRM_INTRO = "Stai per eliminare %d configurazioni di: %s. Le altre specializzazioni e i talenti attivi verranno conservati. Digita NUKE o 123123 per confermare."
locales.itIT.SELECT_SPECS = "Seleziona almeno una specializzazione."
locales.itIT.MERGE_BATCH_INTRO = "Controlla ogni gruppo duplicato delle specializzazioni selezionate e modifica il nome risultante. La prima copia viene rinominata e le altre eliminate."
locales.itIT.SCOPE = "Unisci, Pulisci e Nuke agiscono sulle specializzazioni selezionate."
locales.itIT.NUKE_REQUIRED = "Digita NUKE o 123123 per confermare."
locales.ptBR.HIDE_UNIQUE = "Ocultar builds únicas"
locales.ptBR.LOADOUT_CELL = "Configurações %d"
locales.ptBR.NO_DUPLICATED_GROUPS = "Nenhum grupo duplicado"
locales.ptBR.DUPLICATE_CELL = "Grupos duplicados %d"
locales.ptBR.NUKE_CONFIRM_TITLE = "Nuke — confirmar exclusão"
locales.ptBR.NUKE_CONFIRM_INTRO = "Você vai apagar %d configurações de: %s. As outras especializações e talentos ativos serão mantidos. Digite NUKE ou 123123 para confirmar."
locales.ptBR.SELECT_SPECS = "Selecione pelo menos uma especialização."
locales.ptBR.MERGE_BATCH_INTRO = "Revise cada grupo duplicado das especializações selecionadas e edite o nome resultante. A primeira cópia é renomeada e as outras removidas."
locales.ptBR.SCOPE = "Mesclar, Limpar e Nuke afetam as especializações selecionadas."
locales.ptBR.NUKE_REQUIRED = "Digite NUKE ou 123123 para confirmar."
locales.ruRU.HIDE_UNIQUE = "Скрыть уникальные наборы"
locales.ruRU.LOADOUT_CELL = "Наборы %d"
locales.ruRU.NO_DUPLICATED_GROUPS = "Нет повторяющихся групп"
locales.ruRU.DUPLICATE_CELL = "Повторяющиеся группы %d"
locales.ruRU.NUKE_CONFIRM_TITLE = "Nuke — подтвердить удаление"
locales.ruRU.NUKE_CONFIRM_INTRO = "Будут удалены %d сохранённых наборов специализаций: %s. Другие специализации и активные таланты сохранятся. Введите NUKE или 123123."
locales.ruRU.SELECT_SPECS = "Сначала выберите хотя бы одну специализацию."
locales.ruRU.MERGE_BATCH_INTRO = "Проверьте каждую повторяющуюся группу выбранных специализаций и измените итоговое имя. Первая копия переименуется, остальные будут удалены."
locales.ruRU.SCOPE = "Объединение, очистка и Nuke действуют на выбранные специализации."
locales.ruRU.NUKE_REQUIRED = "Для подтверждения введите NUKE или 123123."
locales.koKR.HIDE_UNIQUE = "고유 구성 숨기기"
locales.koKR.LOADOUT_CELL = "구성 %d개"
locales.koKR.NO_DUPLICATED_GROUPS = "중복 그룹 없음"
locales.koKR.DUPLICATE_CELL = "중복 그룹 %d개"
locales.koKR.NUKE_CONFIRM_TITLE = "Nuke — 삭제 확인"
locales.koKR.NUKE_CONFIRM_INTRO = "저장된 구성 %d개를 다음 전문화에서 삭제합니다: %s. 다른 전문화와 활성 특성은 유지됩니다. NUKE 또는 123123을 입력하세요."
locales.koKR.SELECT_SPECS = "먼저 전문화를 하나 이상 선택하세요."
locales.koKR.MERGE_BATCH_INTRO = "선택한 전문화의 중복 그룹을 확인하고 결과 이름을 수정하세요. 첫 번째 구성은 이름이 변경되고 나머지는 삭제됩니다."
locales.koKR.SCOPE = "병합, 정리 및 Nuke는 선택한 전문화에 적용됩니다."
locales.koKR.NUKE_REQUIRED = "확인하려면 NUKE 또는 123123을 입력하세요."
locales.zhCN.HIDE_UNIQUE = "隐藏独有配置"
locales.zhCN.LOADOUT_CELL = "配置 %d"
locales.zhCN.NO_DUPLICATED_GROUPS = "无重复组"
locales.zhCN.DUPLICATE_CELL = "重复组 %d"
locales.zhCN.NUKE_CONFIRM_TITLE = "Nuke — 确认删除"
locales.zhCN.NUKE_CONFIRM_INTRO = "将删除%d份已保存配置，所属专精：%s。其他专精和当前生效的天赋将保留。输入NUKE或123123以确认。"
locales.zhCN.SELECT_SPECS = "请先选择至少一个专精。"
locales.zhCN.MERGE_BATCH_INTRO = "检查所选专精的每个重复组并编辑合并后的名称。第一份配置将重命名，其余副本将删除。"
locales.zhCN.SCOPE = "合并、清理和Nuke作用于所选专精。"
locales.zhCN.NUKE_REQUIRED = "输入NUKE或123123以确认。"
locales.zhTW.HIDE_UNIQUE = "隱藏獨有配置"
locales.zhTW.LOADOUT_CELL = "配置 %d"
locales.zhTW.NO_DUPLICATED_GROUPS = "無重複群組"
locales.zhTW.DUPLICATE_CELL = "重複群組 %d"
locales.zhTW.NUKE_CONFIRM_TITLE = "Nuke — 確認刪除"
locales.zhTW.NUKE_CONFIRM_INTRO = "將刪除%d份已儲存配置，所屬專精：%s。其他專精和目前生效的天賦將保留。輸入NUKE或123123以確認。"
locales.zhTW.SELECT_SPECS = "請先選擇至少一個專精。"
locales.zhTW.MERGE_BATCH_INTRO = "檢查所選專精的每個重複群組並編輯合併後的名稱。第一份配置將重新命名，其餘副本將刪除。"
locales.zhTW.SCOPE = "合併、清理和Nuke作用於所選專精。"
locales.zhTW.NUKE_REQUIRED = "輸入NUKE或123123以確認。"
locales.enUS.ACTION_PREVIEW_HINT = "Click an action to preview the changes. Nothing is changed until you confirm."
locales.esES.ACTION_PREVIEW_HINT = "Pulsa una acción para revisar los cambios. No se modifica nada hasta que confirmes."
locales.deDE.ACTION_PREVIEW_HINT = "Klicke auf eine Aktion, um die Änderungen vorab zu prüfen. Erst nach deiner Bestätigung wird etwas geändert."
locales.frFR.ACTION_PREVIEW_HINT = "Cliquez sur une action pour prévisualiser les changements. Rien ne sera modifié avant votre confirmation."
locales.itIT.ACTION_PREVIEW_HINT = "Clicca su un’azione per vedere le modifiche in anteprima. Nulla verrà modificato finché non confermi."
locales.ptBR.ACTION_PREVIEW_HINT = "Clique em uma ação para visualizar as alterações. Nada será alterado até você confirmar."
locales.ruRU.ACTION_PREVIEW_HINT = "Нажмите действие, чтобы просмотреть изменения. Ничего не изменится, пока вы не подтвердите."
locales.koKR.ACTION_PREVIEW_HINT = "작업을 클릭하여 변경 내용을 미리 확인하세요. 확인하기 전에는 아무것도 변경되지 않습니다."
locales.zhCN.ACTION_PREVIEW_HINT = "点击操作可预览更改。确认之前不会进行任何修改。"
locales.zhTW.ACTION_PREVIEW_HINT = "點擊操作可預覽變更。確認之前不會進行任何修改。"
locales.enUS.MEMORY_REPORT = "Memory: %s MB · Undo: %d operations, %d builds, %d bytes of text · Talent reads: %d"
locales.esES.MEMORY_REPORT = "Memoria: %s MB · Undo: %d operaciones, %d builds, %d bytes de texto · Lecturas de talentos: %d"
locales.deDE.MEMORY_REPORT = "Speicher: %s MB · Rückgängig: %d Vorgänge, %d Builds, %d Textbytes · Talentabfragen: %d"
locales.frFR.MEMORY_REPORT = "Mémoire : %s Mo · Annuler : %d opérations, %d builds, %d octets de texte · Lectures des talents : %d"
locales.itIT.MEMORY_REPORT = "Memoria: %s MB · Annulla: %d operazioni, %d build, %d byte di testo · Letture dei talenti: %d"
locales.ptBR.MEMORY_REPORT = "Memória: %s MB · Desfazer: %d operações, %d builds, %d bytes de texto · Leituras de talentos: %d"
locales.ruRU.MEMORY_REPORT = "Память: %s МБ · Отмена: %d операций, %d наборов, %d байт текста · Чтений талантов: %d"
locales.koKR.MEMORY_REPORT = "메모리: %s MB · 실행 취소: 작업 %d개, 구성 %d개, 텍스트 %d바이트 · 특성 조회: %d회"
locales.zhCN.MEMORY_REPORT = "内存：%s MB · 撤销：%d次操作，%d份配置，%d字节文本 · 天赋读取：%d次"
locales.zhTW.MEMORY_REPORT = "記憶體：%s MB · 復原：%d次操作，%d份配置，%d位元組文字 · 天賦讀取：%d次"
locales.enGB = locales.enUS
locales.esMX = locales.esES
-- Compatibility alias for clients reporting the older Portuguese locale.
locales.ptPT = locales.ptBR
TM.Locales = locales
TM.locale = GetLocale and GetLocale() or "enUS"
TM.L = locales[TM.locale] or locales.enUS
function TM:T(key, ...)
    local value = self.L[key] or locales.enUS[key] or key
    if select("#", ...) > 0 then return string.format(value, ...) end
    return value
end
